# Generated by Django 3.2.9 on 2021-11-04 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtracker',
            name='atTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
