# Generated by Django 3.2.9 on 2021-11-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_logtracker_attime'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtracker',
            name='isSuccess',
            field=models.BooleanField(default=True),
        ),
    ]
